### ISSUE TITLE
Followed instructions to build on ubuntu 15.10 or Newer for nvidia. Cant seem do get anywhere

### ISSUE THREAD

**Issue by sratra** [Genoil/cpp-ethereum#237]
Hello
Just fyi, Im new to ubuntu and trying to get some familiarity. 
I input all the mentioned commands one by one and it seems to have worked without a snag. The executable has appeared in cpp-ethereum/buid/ethminer.
If I open terminal in the ethminer directory and try to use ethminer --help I get the following message:
"ethminer: command not found".

Any ehlp would be greatly appreciated.

**Comment by sratra** [comment]
OK Ive read on a forum that 10** series nvidia cards require the 8.0 cuda repository. So i redid the etire instructions with the 8.0 repo.
At the end of the "make -j8" commands process I get this :+1: 
```
/home/mining/cpp-ethereum/libethcore/EthashCUDAMiner.cpp: In member function ‘workLoop’:
/home/mining/cpp-ethereum/libethcore/EthashCUDAMiner.cpp:202:96: warning: ‘startN’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   m_miner->search(w.headerHash.data(), upper64OfBoundary, *m_hook, (w.exSizeBits >= 0), startN);
                                                                                                ^
/home/mining/cpp-ethereum/libethcore/EthashCUDAMiner.cpp:199:12: note: ‘startN’ was declared here
   uint64_t startN;
            ^
/tmp/cc6yIQa8.ltrans22.ltrans.o:<artificial>:__fatDeviceText: error: undefined reference to 'fatbinData'
collect2: error: ld returned 1 exit status
ethminer/CMakeFiles/ethminer.dir/build.make:118: recipe for target 'ethminer/ethminer' failed
make[2]: *** [ethminer/ethminer] Error 1
CMakeFiles/Makefile2:493: recipe for target 'ethminer/CMakeFiles/ethminer.dir/all' failed
make[1]: *** [ethminer/CMakeFiles/ethminer.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

```
