### PR TITLE
Add dependencies for macOS compilation

### PR DESCRIPTION
**Pull request by cdalvaro**
This pull request is intended to fix macOS compilation errors.

### CODE REVIEW

**Review by andrusha — APPROVED** [review]
Works on macOS 10.12.5. Followed instructions just as in README.

**Comment by cdalvaro2** [comment]
This pull request solves issue #143

**Comment by ArtSabintsev** [comment]
It looked or looks as if Genoil was dead, so I forked it last night and added a couple changes here and there, including the ones found here.

The fork came after this LONG conversation: https://github.com/ethereum/homebrew-ethereum/issues/116

https://github.com/ArtSabintsev/Ethminer-for-macOS/releases/tag/1.0.1

**Comment by andrusha** [comment]
There is another fork, which seems to be more actively developed, worth looking at it too https://github.com/ethereum-mining/ethminer

**Comment by ArtSabintsev** [comment]
@andrusha that's awesome! Happy someone else decided to take the initiative as well!
