### ISSUE TITLE
How to compile on OSX?

### ISSUE THREAD

**Issue by gateway** [Genoil/cpp-ethereum#143]
Anyone able to get this to compile on OSX yet or have a binary to share?

I did 

cmake -DETHASHCL=1 -DGUI=0
make -j4

and it failed to compile with 

```
  "typeinfo for dev::Worker", referenced from:
      typeinfo for dev::eth::EthashCPUMiner in EthashCPUMiner.cpp.o
      typeinfo for dev::eth::EthashGPUMiner in EthashGPUMiner.cpp.o
  "vtable for dev::Worker", referenced from:
      dev::eth::EthashCPUMiner::EthashCPUMiner(std::__1::pair<dev::eth::GenericFarmFace<dev::eth::EthashProofOfWork>*, unsigned int> const&) in EthashCPUMiner.cpp.o
      dev::Worker::~Worker() in EthashCPUMiner.cpp.o
      dev::eth::EthashGPUMiner::EthashGPUMiner(std::__1::pair<dev::eth::GenericFarmFace<dev::eth::EthashProofOfWork>*, unsigned int> const&) in EthashGPUMiner.cpp.o
      dev::Worker::~Worker() in EthashGPUMiner.cpp.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libethcore/libethcore.dylib] Error 1
make[1]: *** [libethcore/CMakeFiles/ethcore.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 83%] Building CXX object libdevcore/CMakeFiles/devcore.dir/TransientDirectory.cpp.o
[ 86%] Building CXX object libdevcore/CMakeFiles/devcore.dir/TrieCommon.cpp.o
[ 88%] Building CXX object libdevcore/CMakeFiles/devcore.dir/TrieDB.cpp.o
[ 90%] Building CXX object libdevcore/CMakeFiles/devcore.dir/TrieHash.cpp.o
2 warnings generated.
[ 93%] Building CXX object libdevcore/CMakeFiles/devcore.dir/Worker.cpp.o
[ 95%] Linking CXX shared library libdevcore.dylib
[ 95%] Built target devcore
make: *** [all] Error 2
```

any suggestions?

**Comment by avatar-lavventura** [comment]
Any update on this issue? I have the similar error:

```
  "typeinfo for dev::Worker", referenced from:
      typeinfo for dev::eth::EthashCPUMiner in EthashCPUMiner.cpp.o
      typeinfo for dev::eth::EthashGPUMiner in EthashGPUMiner.cpp.o
  "vtable for dev::Worker", referenced from:
      dev::eth::EthashCPUMiner::EthashCPUMiner(std::__1::pair<dev::eth::GenericFarmFace<dev::eth::EthashProofOfWork>*, unsigned int> const&) in EthashCPUMiner.cpp.o
      dev::Worker::~Worker() in EthashCPUMiner.cpp.o
      dev::eth::EthashGPUMiner::EthashGPUMiner(std::__1::pair<dev::eth::GenericFarmFace<dev::eth::EthashProofOfWork>*, unsigned int> const&) in EthashGPUMiner.cpp.o
      dev::Worker::~Worker() in EthashGPUMiner.cpp.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libethcore/libethcore.dylib] Error 1
make[1]: *** [libethcore/CMakeFiles/ethcore.dir/all] Error 2
```

**Comment by gateway** [comment]
I think this project has been abandon??

**Comment by bfleming** [comment]
I managed to compile it on 10.11.6 yesterday. The problem looks to be that the linker commands aren't linking libraries that include needed functions. The way I did it was to grep for the missing functions to find the needed library and manually run the linker command, (found in link.txt of the subdirectories), adding the missing library. I don't know enough about the cmake process to contribute a patch, but I can certainly do more testing.

**Comment by themondays** [comment]
Can you please drop here a details about missing functions?

**Comment by bfleming** [comment]
In my case, I had several more errors to fix than above.
For the above example, it looks like it's not including libdevcore.dylib, (library with dev::Worker function), in the command for libethcore. Try manually running the command contained in cpp-ethereum/build/libethcore/CMakeFiles/ethcore.dir/link.txt adding the path to the libdevcore library, (which should be in cpp-ethereum/build/libdevcore/). Run the command while in the cpp-ethereum/build/libethcore directory.

**Comment by durd** [comment]
Trying to compile on 10.12.5 but couldnt get past some json-functions :/
libethcore was not the only library needing help with the link.txt, also had to edit the link.txt for libdevcore and libstratum which also missed them json functions. I have installed the libjson-rpc-cpp via brew so not sure whats missing.

**Comment by bfleming** [comment]
It might need help finding one of the json libs or it's not in link.txt. Can you post the error?

**Comment by durd** [comment]
I tried adding the path to the dylib to the link.txt for libstratum but that didn't help.
Here's the error:
`comp:cpp-ethereum-master david$ make -j4
[ 10%] Built target ethash
[ 17%] Built target ethash-cl
[ 17%] Built target BuildInfo.h
[ 19%] Linking CXX shared library libethstratum.dylib
Undefined symbols for architecture x86_64:
  "Json::Value::null", referenced from:
      EthStratumClient::processReponse(Json::Value&) in EthStratumClient.cpp.o
      EthStratumClientV2::processReponse(Json::Value&) in EthStratumClientV2.cpp.o
  "Json::Value::Value(Json::ValueType)", referenced from:
      EthStratumClient::readResponse(boost::system::error_code const&, unsigned long) in EthStratumClient.cpp.o
      EthStratumClient::processReponse(Json::Value&) in EthStratumClient.cpp.o
      EthStratumClientV2::workLoop() in EthStratumClientV2.cpp.o
      EthStratumClientV2::processReponse(Json::Value&) in EthStratumClientV2.cpp.o
  "Json::Value::Value(char const*)", referenced from:
      EthStratumClient::processReponse(Json::Value&) in EthStratumClient.cpp.o
      EthStratumClientV2::processReponse(Json::Value&) in EthStratumClientV2.cpp.o
  "Json::Value::Value(bool)", referenced from:
      EthStratumClient::processReponse(Json::Value&) in EthStratumClient.cpp.o
      EthStratumClientV2::processReponse(Json::Value&) in EthStratumClientV2.cpp.o
  "Json::Value::Value(int)", referenced from:
      EthStratumClient::processReponse(Json::Value&) in EthStratumClient.cpp.o
      EthStratumClientV2::processReponse(Json::Value&) in EthStratumClientV2.cpp.o
  "Json::Value::~Value()", referenced from:
      EthStratumClient::readResponse(boost::system::error_code const&, unsigned long) in EthStratumClient.cpp.o
      EthStratumClient::processReponse(Json::Value&) in EthStratumClient.cpp.o
      EthStratumClientV2::workLoop() in EthStratumClientV2.cpp.o
      EthStratumClientV2::processReponse(Json::Value&) in EthStratumClientV2.cpp.o
  "Json::Value::operator=(Json::Value)", referenced from:
      EthStratumClient::processReponse(Json::Value&) in EthStratumClient.cpp.o
      EthStratumClientV2::processReponse(Json::Value&) in EthStratumClientV2.cpp.o
  "Json::Reader::parse(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Json::Value&, bool)", referenced from:
      EthStratumClient::readResponse(boost::system::error_code const&, unsigned long) in EthStratumClient.cpp.o
      EthStratumClientV2::workLoop() in EthStratumClientV2.cpp.o
  "Json::Reader::Reader()", referenced from:
      EthStratumClient::readResponse(boost::system::error_code const&, unsigned long) in EthStratumClient.cpp.o
      EthStratumClientV2::workLoop() in EthStratumClientV2.cpp.o
  "Json::Value::get(char const*, Json::Value const&) const", referenced from:
      EthStratumClient::processReponse(Json::Value&) in EthStratumClient.cpp.o
      EthStratumClientV2::processReponse(Json::Value&) in EthStratumClientV2.cpp.o
  "Json::Value::get(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Json::Value const&) const", referenced from:
      EthStratumClientV2::processReponse(Json::Value&) in EthStratumClientV2.cpp.o
  "Json::Value::get(unsigned int, Json::Value const&) const", referenced from:
      EthStratumClient::processReponse(Json::Value&) in EthStratumClient.cpp.o
      EthStratumClientV2::processReponse(Json::Value&) in EthStratumClientV2.cpp.o
  "Json::Value::asInt() const", referenced from:
      EthStratumClient::processReponse(Json::Value&) in EthStratumClient.cpp.o
      EthStratumClientV2::processReponse(Json::Value&) in EthStratumClientV2.cpp.o
  "Json::Value::asBool() const", referenced from:
      EthStratumClient::processReponse(Json::Value&) in EthStratumClient.cpp.o
      EthStratumClientV2::processReponse(Json::Value&) in EthStratumClientV2.cpp.o
  "Json::Value::isArray() const", referenced from:
      EthStratumClient::processReponse(Json::Value&) in EthStratumClient.cpp.o
      EthStratumClientV2::processReponse(Json::Value&) in EthStratumClientV2.cpp.o
  "Json::Value::asDouble() const", referenced from:
      EthStratumClient::processReponse(Json::Value&) in EthStratumClient.cpp.o
      EthStratumClientV2::processReponse(Json::Value&) in EthStratumClientV2.cpp.o
  "Json::Value::asString() const", referenced from:
      EthStratumClient::processReponse(Json::Value&) in EthStratumClient.cpp.o
      EthStratumClientV2::processReponse(Json::Value&) in EthStratumClientV2.cpp.o
  "Json::Reader::getFormattedErrorMessages() const", referenced from:
      EthStratumClient::readResponse(boost::system::error_code const&, unsigned long) in EthStratumClient.cpp.o
      EthStratumClientV2::workLoop() in EthStratumClientV2.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libstratum/libethstratum.dylib] Error 1
make[1]: *** [libstratum/CMakeFiles/ethstratum.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 65%] Built target devcore
[ 91%] Built target ethcore
make: *** [all] Error 2`

**Comment by bfleming** [comment]
This looks like it needs the jsoncpp library. Try installing with brew or adding it to the linker command if it's already installed.

**Comment by durd** [comment]
Ah, I added the json-rpc-cpp-lib to the link.txt. Now i got it compiled! Thanks :)
```
comp:ethminer david$ ./ethminer -G --opencl-device 1 -M
*snip*
Trial 1... 1919190
Trial 2... 1919190
Trial 3... 2009770
Trial 4... 1919829
Trial 5... 1919190
min/mean/max: 1919190/1937433/2009770 H/s
inner mean: 1309866 H/s
```

**Comment by viktorkodasc** [comment]
@durd Does it work on mbp 2016? How much vidmem do you have?

**Comment by durd** [comment]
It was the cheapest GPU Apple has for the model:
`Radeon Pro 450 with 2GB of GDDR5`

I'm not sure what `inner mean` means, but I just ran the test again it more than halved from my previous run above.

**Comment by durd** [comment]
@viktorkodasc Are you really using the Radeon? My Intel has 1,5GB (1536MB).

Run `ethminer --list-devices -G` and take note of the ID for the Radeon, and use that ID with the flag `--opencl-device <ID>` when running `ethminer`.
```
comp:ethminer david$ ./ethminer --list-devices -G
Genoil's ethminer 0.9.41-genoil-1.1.7
=====================================================================
Forked from github.com/ethereum/cpp-ethereum
CUDA kernel ported from Tim Hughes' OpenCL kernel
With contributions from nicehash, nerdralph, RoBiK and sp_

Please consider a donation to:
ETH: 0xeb9310b185455f863f526dab3d245809f6854b4d

[OPENCL]:
Listing OpenCL devices.
FORMAT: [deviceID] deviceName
[0] Intel(R) HD Graphics 530
	CL_DEVICE_TYPE: GPU
	CL_DEVICE_GLOBAL_MEM_SIZE: 1610612736
	CL_DEVICE_MAX_MEM_ALLOC_SIZE: 402653184
	CL_DEVICE_MAX_WORK_GROUP_SIZE: 256
[1] AMD Radeon Pro 455 Compute Engine
	CL_DEVICE_TYPE: GPU
	CL_DEVICE_GLOBAL_MEM_SIZE: 2147483648
	CL_DEVICE_MAX_MEM_ALLOC_SIZE: 536870912
	CL_DEVICE_MAX_WORK_GROUP_SIZE: 256
```

**Comment by viktorkodasc** [comment]
@durd I have only integrated graphics:
[OPENCL]:
Listing OpenCL devices.
FORMAT: [deviceID] deviceName
[0] Iris Pro
	CL_DEVICE_TYPE: GPU
	CL_DEVICE_GLOBAL_MEM_SIZE: 1610612736
	CL_DEVICE_MAX_MEM_ALLOC_SIZE: 402653184
	CL_DEVICE_MAX_WORK_GROUP_SIZE: 512

**Comment by viktorkodasc** [comment]
There is a combination of flags that enable CPU codepath:
./ethminer --allow-opencl-cpu --opencl-device 0 -G ...
This overcomes issue with DAG buffer allocation:
[OPENCL]:Found suitable OpenCL device [Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz] with 17179869184 bytes of GPU memory
But hangs on:
stratum  Received new job #7a3b6c75
Nothing happens after this, so it doesn't work on CPU anyway.

**Comment by durd** [comment]
According to Wikipedia, only the 15" MBP has a second Radeon GPU. The 13" runs an integrated Intel Iris.

**Comment by rabarar** [comment]
so how did folks resolve these errors:

**Comment by mickiewicz** [comment]
@durd could you please explain in details how have you managed to compile it? I'm getting the same error as you but with libethcore. Thx!

**Comment by rabarar** [comment]
I got it to build by editing the ethcore link file and adding the libdevcore.dylib to the link file

**Comment by mickiewicz** [comment]
@rabarar and where did you find libdevcore.dylib? Because in my cpp-ethereum directory there is no such file.

**Comment by nikbass** [comment]
Hello everyone. I'm also trying to compliment it but I'm mistaken and I do not understand how to continue ...

**Comment by proteins247** [comment]
After trying `make` in the build dir, you need to edit the link.txt files in the subdirectories of build.

    $ find -name link.txt
    ./ethminer/CMakeFiles/ethminer.dir/link.txt
    ./libdevcore/CMakeFiles/devcore.dir/link.txt
    ./libethash/CMakeFiles/ethash.dir/link.txt
    ./libethash-cl/CMakeFiles/ethash-cl.dir/link.txt
    ./libethcore/CMakeFiles/ethcore.dir/link.txt
    ./libstratum/CMakeFiles/ethstratum.dir/link.txt

Which of the files you edit depends on the error the compiler spits out. For instance, building libethstratum gave me the json library error, so I added `/usr/local/lib/libjsoncpp.a` to the command contained in `./libstratum/CMakeFiles/ethstratum.dir/link.txt`

You can then attempt to compile to address the next error.

Subsequent errors gave me problems linking to functions defined within cpp-ethereum. Similarly, find the `link.txt` file corresponding to the error. There, put the path to the .dylib containing the missing function. All the .dylibs were contained in `build`

You can find which relevant dylib using grep: `grep -r FUNCTIONNAME`

**Comment by rabarar** [comment]
For those wanting a complete step-by-step, here’s what I did to make it work:

git clone cpp-ethereum
brew install cryptopp jsoncpp libjson-rpc-cpp qt qt5 leveldb boost
cd cpp-ethereum
mkdir build
cd build
cmake .. (you may need to turn on ETHSTRATUM  'cmake .. -DETHSTRATUM=1')

vi libethcore/CMakeFiles/ethcore.dir/link.txt

        add ../libdevcore/libdevcore.dylib

vi libstratum/CMakeFiles/ethstratum.dir/link.txt

        add /usr/local/lib/libjsoncpp.a
        add ../libdevcore/libdevcore.dylib
        add ../libethcore/libethcore.dylib

make

Here's what your link files should look like after editing

libethcore link.txt:

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -std=c++11 -Wall -Wno-unknown-pragmas -Wextra -DSHAREDLIB -fPIC -O3 -DNDEBUG -DETH_RELEASE -dynamiclib -Wl,-headerpad_max_install_names  -o libethcore.dylib -install_name /Users/robert/src/ethereum/cpp-ethereum/build/libethcore/libethcore.dylib CMakeFiles/ethcore.dir/BlockInfo.cpp.o CMakeFiles/ethcore.dir/Common.cpp.o CMakeFiles/ethcore.dir/Ethash.cpp.o CMakeFiles/ethcore.dir/EthashAux.cpp.o CMakeFiles/ethcore.dir/EthashCPUMiner.cpp.o CMakeFiles/ethcore.dir/EthashCUDAMiner.cpp.o CMakeFiles/ethcore.dir/EthashGPUMiner.cpp.o CMakeFiles/ethcore.dir/EthashSealEngine.cpp.o CMakeFiles/ethcore.dir/Miner.cpp.o CMakeFiles/ethcore.dir/Params.cpp.o CMakeFiles/ethcore.dir/Sealer.cpp.o ../libdevcore/libdevcore.dylib ../libethash-cl/libethash-cl.dylib ../libethash/libethash.dylib /usr/local/lib/libcryptopp.dylib -framework OpenCL

libstratum link.txt:

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -std=c++11 -Wall -Wno-unknown-pragmas -Wextra -DSHAREDLIB -fPIC -O3 -DNDEBUG -DETH_RELEASE -dynamiclib -Wl,-headerpad_max_install_names  -o libethstratum.dylib -install_name /Users/robert/src/ethereum/cpp-ethereum/build/libstratum/libethstratum.dylib CMakeFiles/ethstratum.dir/EthStratumClient.cpp.o CMakeFiles/ethstratum.dir/EthStratumClientV2.cpp.o CMakeFiles/ethstratum.dir/ethstratum_autogen/moc_compilation.cpp.o /usr/local/lib/libboost_system-mt.a  /usr/local/lib/libjsoncpp.a /usr/local/lib/libboost_thread-mt.a /usr/local/lib/libboost_regex-mt.a  ../libdevcore/libdevcore.dylib ../libethcore/libethcore.dylib


This successfully built on OS X with strtatum 

Best,
Rob

**Comment by proteins247** [comment]
the miner performance on OSX is nearly an order of magnitude less than on Windows in my experience. 3.4 MH/s vs 24 MH/s.

**Comment by sahara108** [comment]
@proteins247 then how about Windows vs Ubuntu?

**Comment by proteins247** [comment]
Since Linux distributions, especially Ubuntu, are recommended alongside windows for mining, I assume that the performance would be comparable.

**Comment by S73417H** [comment]
#207 will fix compilation for OSX
