### ISSUE TITLE
Build fails at ubuntu 16.10

### ISSUE THREAD

**Issue by Visgean** [Genoil/cpp-ethereum#110]
partial log:

```
 ^~~~~~~~~~~~~
In file included from /home/visgean/p/cpp-ethereum/ethminer/main.cpp:39:0:
/home/visgean/p/cpp-ethereum/ethminer/MinerAux.h: In member function ‘void MinerCLI::doStratum()’:
/home/visgean/p/cpp-ethereum/ethminer/MinerAux.h:1024:14: warning: suggest explicit braces to avoid ambiguous ‘else’ [-Wparentheses]
      else if (client.waitState() == MINER_WAIT_STATE_WORK)
              ^
/home/visgean/p/cpp-ethereum/ethminer/MinerAux.h:1059:14: warning: suggest explicit braces to avoid ambiguous ‘else’ [-Wparentheses]
      else if (client.waitState() == MINER_WAIT_STATE_WORK)
              ^
[100%] Linking CXX executable ethminer
../libethcore/libethcore.so: error: undefined reference to 'pthread_create'
../libstratum/libethstratum.so: error: undefined reference to 'pthread_join'
../libstratum/libethstratum.so: error: undefined reference to 'pthread_detach'
collect2: error: ld returned 1 exit status
ethminer/CMakeFiles/ethminer.dir/build.make:112: recipe for target 'ethminer/ethminer' failed
make[2]: *** [ethminer/ethminer] Error 1
CMakeFiles/Makefile2:436: recipe for target 'ethminer/CMakeFiles/ethminer.dir/all' failed
make[1]: *** [ethminer/CMakeFiles/ethminer.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

full log: https://gist.github.com/Visgean/9b87247e4e2013ba72f214005274a60e

**Comment by gislikarl** [comment]
Same Here, this is what I'm getting as well. Oddly, CMAKE works just fine.

`../libethcore/libethcore.so: error: undefined reference to 'pthread_create'
../libstratum/libethstratum.so: error: undefined reference to 'pthread_join'
../libstratum/libethstratum.so: error: undefined reference to 'pthread_detach'
collect2: error: ld returned 1 exit status
ethminer/CMakeFiles/ethminer.dir/build.make:112: recipe for target 'ethminer/ethminer' failed
make[2]: *** [ethminer/ethminer] Error 1
CMakeFiles/Makefile2:436: recipe for target 'ethminer/CMakeFiles/ethminer.dir/all' failed
make[1]: *** [ethminer/CMakeFiles/ethminer.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by Visgean** [comment]
how did you manage to do it with cmake?

**Comment by Visgean** [comment]
I mean what was the command you used.

**Comment by gislikarl** [comment]
@Visgean I used the cmake command from the instructions
> cmake -DBUNDLE=miner ..

Thing is that they renamed package libjson-rpc-cpp-dev to libjsonrpccpp-dev in Ubuntu 16.04 so after installing that package, cmake runs fine. make however does not :(

**Comment by Visgean** [comment]
that is what I used. the command that fails is "$ make -j8"

**Comment by gislikarl** [comment]
Same here

**Comment by mrtizmo** [comment]
Try this cmake command:

`cmake -DBUNDLE=miner -DCMAKE_CXX_FLAGS="-std=c++11 -pthread" ..`

**Comment by gislikarl** [comment]
Damn, that did it. Finally it compiled. Thank you very much :D

**Comment by Visgean** [comment]
Thanks, that works. I will PR to readme.

**Comment by Prostu2** [comment]
@mrtizmo can u please tell me how can i compile it on ubuntu but to work on centos and other linux too ?!

**Comment by Unandro** [comment]
how compile on ubuntu 16.10 ?
I get error
`[100%] Linking CXX executable ethminer
../libdevcore/libdevcore.so: error: undefined reference to 'Json::FastWriter::write(Json::Value const&)'
../libdevcore/libdevcore.so: error: undefined reference to 'Json::Value::operator[](std::string const&)'
../libstratum/libethstratum.so: error: undefined reference to 'Json::Reader::parse(std::string const&, Json::Value&, bool)'
../libstratum/libethstratum.so: error: undefined reference to 'Json::Reader::getFormattedErrorMessages() const'
../libstratum/libethstratum.so: error: undefined reference to 'Json::Value::get(std::string const&, Json::Value const&) const'`

**Comment by mrtizmo** [comment]
@Unandro your linker isn't finding the json cpp library. Make sure you have the correct library installed. In Ubuntu 16.10, you need to use Ubuntu's package named libjsonrpccpp-dev instead of PPA's libjson-rpc-cpp-dev.

These are the json packages that I have installed:
libjsoncpp-dev libjsonrpccpp-dev libjsonrpccpp-tools

**Comment by Unandro** [comment]
i know about different package names in different ubuntu releases.
`$ dpkg -l | grep 'libjsonrpccpp-dev\|libjsoncpp-dev\|libjsonrpccpp-tools'
ii  libjsoncpp-dev:amd64 1.7.2-1
ii  libjsonrpccpp-dev  0.7.0-1
ii  libjsonrpccpp-tools 0.7.0-1`
this error get after upgrade from 16.04 to 16.10, and it haunts me )

**Comment by andoriyu** [comment]
@Unandro have you ever fixed that issue?

**Comment by Unandro** [comment]
@andoriyu no, the only option I found is build on an earlier version of the distribution

**Comment by andoriyu** [comment]
@Unandro so here is the problem — libs compiled with different version of GCC. GCC borked their ABI twice. So try using different GCC (override CC and CXX before running cmake). GCC5 worked for me on 17.04. Please note that CUDA won't compile on GCC6.

**Comment by Unandro** [comment]
@andoriyu thanks! I can do it. in 17.04
`cmake -DBUNDLE=cudaminer -DCMAKE_C_COMPILER=/usr/bin/gcc-5 -DCMAKE_CXX_COMPILER=/usr/bin/g++-5 ..`
Also need install libcryptopp-dev from ppa, because default repo has only libcrypto++-dev and it causes conflict

**Comment by wujun** [comment]
@mrtizmo It works for me, thanks
