### ISSUE TITLE
Ethminer 1.1.4 / Cuda8 Stops at random

### ISSUE THREAD

**Issue by kruisdraad** [Genoil/cpp-ethereum#54]
Hi @Genoil ,

I am running with the Cuda8 RC in combination with driver 367.27 (Ubuntu 16.04) with some highly set overclocking using a GTX1070FE card. After loads of tuning i managed to get the card stable running at nearly 32MH/s but at random (after hours) it just quits and starts to do 0 MH/s.

Just before this happens the following error (?) is thrown:

[OPENCL]:clEnqueueMapBuffer(-36)

I have no idea why, but it feels like a bug since it does work for hours and hours at stable hashing rates. First i thought it might be the GDM or screensaver doing something, but after disabling it and another few hours of mining it quit again.

Any idea's what area this might be?

**Comment by Genoil** [comment]
please try running it on stock clocks for extended periods to rule out any hardware related crashes.

32MH is pretty neat though.

**Comment by kruisdraad** [comment]
Its was an opencl error returning

```
[OPENCL]:clEnqueueuMapBuffer(-36)
```

I've seen this error in the past (google) with people that could not load the DAG file at all and the miner not starting. My primary question is if you know what would do such a thing (changes in DAG, reloads, etc?)

Ill go and build the version from master instead of from branch 110, perhaps its just something in this new release that makes it borky. This version i grabbed directly as i read somewhere it was linked to Cuda8 (?) I am pretty sure its not a hardware related crash as i am currently testing with a single GPU and have the onboard GPU disabled. I am running X/GDM so i can manage the card using nvidia-settings. If i go passed the system specs i get direct crashes and the GDM goes unresponsive to as it uses the same driver.

**Comment by Genoil** [comment]
enqueuemapbuffer is called many times during mining, to set and reset the search result buffers. -36 means CL_INVALID_COMMAND_QUEUE. Not sure what causes this.  

Your best workaround is actually using the native CUDA kernel. You'll have to build using -DBUNDLE=cudaminer. This can be a bit troublesome on anything but ubuntu 14, but hopefully cuda 8 rc is easier on you.  Check the issues of this repo for possible fixes. Then once you get it built, replace the -G flag with -U. It should give you some extra hashrate too. Really curious btw abotu the performance on stocks clocks. The only thing I know now is about 27.6MH using OpenCL.

If you want to try 1.0.8 with -DBUNLDE=cudaminer, build with -DCOMPUTE=61 as compute 6.1 isn't in the default list of supported compute platforms on that release.

**Comment by kruisdraad** [comment]
Yeah i am thinking its a timing/driver issue in combination with Cuda8, but i have a setup thats 99% stable now so i really dont wanna restarted with older ubuntu or start changing stuff.

I've actually writting a long post on the ETHash performance and mentoined stock results. I have 3 major setpoints:

1: Stock, not doing anything. OpenCL -> 22 MH/s
2: Stock, just using SMI max clocks (-ac) but _NO_ overclocking and again OpenCL -> 26MH/s
3: Overclocking, just using the API with the max settings i was able to run it stable, OpenCL -> 32MH/s using 1.1.4
4. The same as 3, but with 1.0.8 gets you alternating 20.87 and 31.39 (so average 31MH/s). But the startup of 1.1.4 is a LOT faster. 1.1.4 only takes 10 seconds while 1.0.8 DAG loading over an minute.

Yeah, sadly i've got 16.04 but i do have Cuda8 RC successfully installed . I was not able to compile the CUDA at all (somehow i am missed files and i couldnt figure out why)

Ill retry to CUDA build and report back the error, perhaps you hava an clue on that.

In addition, i have 3 rigs each with 6 1070's as of later today. I'd be happy to share a rig for testing / codefixes / tuning if that helps you.

**Comment by kruisdraad** [comment]
Cuda build failed on:

NVCC Fatal : redefinition of argument 'std'

at ethash-cuda_gernated_ethash_cuda_miner_kernel.cu.o

**Comment by Genoil** [comment]
Check the fix described here: https://github.com/Genoil/cpp-ethereum/issues/49

I should move these Linux build issues to the top of my todo list...

**Comment by kruisdraad** [comment]
That fixed the build on CUDA, however Cuda is trying to modprobe nvidia_361_uvm however i dont have that driver used (but it was installed from the CUDA8 defaults) would i need to revert back to 361 version perhaps?

**Comment by Genoil** [comment]
perhaps? i mostly use windows so i wouldn't know. I'm not on IRC, but I use gitter occoasionally.

**Comment by kruisdraad** [comment]
Well i tried windows, but it either crashes and with the best of things perhaps you get 1MH/s so Windows isnt really the way to go with these new cards. But if you have tricks to get it working under Windows then i do like to hear them as its a lot easier/stable under Windows then with linux (for me then)

**Comment by Genoil** [comment]
you'll have to wait a few weeks until MS ships WDDM 2.1 with a win10 update  and Nvidia ships a supporting driver. did it work out with the linux 361 driver?

**Comment by kruisdraad** [comment]
i am currently at work and i rather not brake my currently working setup ( i can make a daemon wrapper that restarts the miner then it happens ) but i have 2 more rigs that are still not installed. I will try the 361 approuch with CUDA8 when i get home. Ill keep you updated.

I'd be happy to write a manpage for this if you want.

**Comment by Genoil** [comment]
cool thx. btw where did you write that post you were referring to?

**Comment by kruisdraad** [comment]
Just basics here:

https://forum.ethereum.org/discussion/7722/gtx-1070-fe-mining-benchmarks

Will write a more detailed with an howto later

**Comment by kruisdraad** [comment]
I've recompliled 1.1.4 and 1.0.8 on the working system and its still hanging after 3 - 4 hours, same error every time. I think after the CL_INVALID_COMMAND_QUEUE ethminer does not retry the command and therefor just hangs

the program should either die (watchdog/detection) or better retry first. Would such a thing be possible (i have no idea what the code does, just pitching here). I could write a wrapper arround the ethminer looking at the output and killing/restarting it which it logs this error, but that is the bad fix ofc.

The driver seems stable and even with a base clock it stops. If the driver crashes i wouldnt be able to restart ethminer, at least in real crashes like i had before with overclock tests it didnt and required a reboot.

Later tonight tests with 18 GPU's and with 361 driver base and Cuda8. Ill keep you posted.

**Comment by kruisdraad** [comment]
I have CUDA working now, or at least i found the issue that wouldnt allow the startup

someone hardcoded the driver detection based on a different file name set, hard to explain but here goes:

Cuda8 installs driver 361 but names it nvidia_361 in DKMS
Driver installer installs driver 367 but names it nvidia (without a version)

ethminer starts up and for some reason wants to do a modprode for 361 even though 367 is already loaded up. Liked a detection mismatch and trying to (think) and get a better version loaded, which fails as the card is not even supported and the never is already loaded.

So the new version is there, it just can find it ... so lets grab an axe and make sure he gets it:

```
   87  cd /lib/modules/4.2.0-38-generic/updates/dkms/
   88  mkdir old
   89  mv nvidia_361* old/
   90  ln -s nvidia.ko nvidia_361.ko
   92  ln -s nvidia-modeset.ko nvidia_361_modeset.ko
   93  ln -s nvidia-modeset.ko nvidia_361-modeset.ko
   94  ln -s nvidia-drm.ko nvidia_361_drm.ko
   95  ln -s nvidia-uvm.ko nvidia_361_uvm.ko
```

I dont need 361, so i can do this without any problems (any GTX10xx needs 367+) et voila the version matches, no more modprobe and it starts. I've compiled 1.0.8 with CUDA for now and gonna  do some baseclock testing which my other rig runs with openCL and see what the differences are

**Comment by kruisdraad** [comment]
Update: 1.0.8 GTX1070 base clocks, no tuning (default defaults) gets me 160MH/s flat out. The DAG loading takes ages though, but that was on OpenCL 1.0.8 too and not with 1.1.4. So far no crashes or buffer problems like OpenCL

**Comment by Genoil** [comment]
that's the 26.7MH/s vaulter reported earlier.

the 1.0 versions all have single threaded CPU-based DAG generation, so yes that does take ages.

**Comment by kruisdraad** [comment]
Ok, i now have Cuda with default ethminer settings, but tuning the GPU up op 80% of i did with NVidia and i am getting : 192,55MH/s which is in line of the 32MH/s in OpenCL ... but it seems a lot more stable with less overclocking. Ill need to try and see if i can push it over the 200 (which shouldn't be a problem, just need time for AsI to find the right combo for that)

**Comment by kruisdraad** [comment]
after testing a while running stock it seems Cuda is more stable, however at some point it still crashes on one of the machines. I do not know it its the risers, the card, driver or the miner. The error onder Cuda:

Invalid memory access

But it does not list on which card. I got the same errors at heavy overclocking as if the card is not responding at that point. Sadly it did not log on which card the problem lies so exchanging it is something troublesome. I think the card resets bases on the driver information:

[ 2318.031672] NVRM: GPU at PCI:0000:03:00: GPU-a470b00f-64ec-0042-ea45-cc40c38c0df3
[ 2318.031683] NVRM: GPU Board Serial Number: 032211xxxxxxx
[ 2318.031690] NVRM: Xid (PCI:0000:03:00): 31, Ch 0000001b, engmask 00000101, intr 10000000

I've seen this card borking up more, with all the overclocking attempts i've done them all except this one.

**Comment by kruisdraad** [comment]
This issue was related to an issue with NVRM itself and has now been patched. It does not related to ethminer
