### ISSUE TITLE
Can't build on Ubuntu 16.10

### ISSUE THREAD

**Issue by manuelpuyol** [Genoil/cpp-ethereum#146]
I'm  using Ubuntu 16.10 with GNOME Shell 3.20.4
When I run `make` on the build dir I have this error
I have all dependencies installed..

 ```
/tmp/ccZfigRN.ltrans0.ltrans.o:<artificial>:function FarmClient::eth_submitWork(std::string const&, std::string const&, std::string const&): error: undefined reference to 'Json::Value::Value(std::string const&)'
/tmp/ccZfigRN.ltrans0.ltrans.o:<artificial>:function FarmClient::eth_submitWork(std::string const&, std::string const&, std::string const&): error: undefined reference to 'Json::Value::Value(std::string const&)'
/tmp/ccZfigRN.ltrans0.ltrans.o:<artificial>:function FarmClient::eth_submitWork(std::string const&, std::string const&, std::string const&): error: undefined reference to 'Json::Value::Value(std::string const&)'
/tmp/ccZfigRN.ltrans0.ltrans.o:<artificial>:function FarmClient::eth_submitWork(std::string const&, std::string const&, std::string const&): error: undefined reference to 'jsonrpc::Client::CallMethod(std::string const&, Json::Value const&)'
/tmp/ccZfigRN.ltrans0.ltrans.o:<artificial>:function FarmClient::eth_submitWork(std::string const&, std::string const&, std::string const&): error: undefined reference to 'Json::Value::toStyledString() const'
/tmp/ccZfigRN.ltrans0.ltrans.o:<artificial>:function FarmClient::eth_submitWork(std::string const&, std::string const&, std::string const&): error: undefined reference to 'jsonrpc::JsonRpcException::JsonRpcException(int, std::string const&)'
/tmp/ccZfigRN.ltrans0.ltrans.o:<artificial>:function MinerCLI::doFarm(dev::eth::MinerType, std::string&, unsigned int): error: undefined reference to 'jsonrpc::HttpClient::HttpClient(std::string const&)'
/tmp/ccZfigRN.ltrans0.ltrans.o:<artificial>:function MinerCLI::doFarm(dev::eth::MinerType, std::string&, unsigned int): error: undefined reference to 'jsonrpc::HttpClient::HttpClient(std::string const&)'
/tmp/ccZfigRN.ltrans0.ltrans.o:<artificial>:function MinerCLI::doFarm(dev::eth::MinerType, std::string&, unsigned int): error: undefined reference to 'Json::Value::Value(std::string const&)'
/tmp/ccZfigRN.ltrans0.ltrans.o:<artificial>:function MinerCLI::doFarm(dev::eth::MinerType, std::string&, unsigned int): error: undefined reference to 'jsonrpc::Client::CallMethod(std::string const&, Json::Value const&)'
/tmp/ccZfigRN.ltrans0.ltrans.o:<artificial>:function MinerCLI::doFarm(dev::eth::MinerType, std::string&, unsigned int): error: undefined reference to 'jsonrpc::Client::CallMethod(std::string const&, Json::Value const&)'
/tmp/ccZfigRN.ltrans0.ltrans.o:<artificial>:function MinerCLI::doFarm(dev::eth::MinerType, std::string&, unsigned int): error: undefined reference to 'Json::Value::asString() const'
/tmp/ccZfigRN.ltrans0.ltrans.o:<artificial>:function MinerCLI::doFarm(dev::eth::MinerType, std::string&, unsigned int): error: undefined reference to 'Json::Value::asString() const'
/tmp/ccZfigRN.ltrans0.ltrans.o:<artificial>:function MinerCLI::doFarm(dev::eth::MinerType, std::string&, unsigned int): error: undefined reference to 'Json::Value::asString() const'
/tmp/ccZfigRN.ltrans0.ltrans.o:<artificial>:function MinerCLI::doFarm(dev::eth::MinerType, std::string&, unsigned int): error: undefined reference to 'Json::Value::toStyledString() const'
/tmp/ccZfigRN.ltrans0.ltrans.o:<artificial>:function MinerCLI::doFarm(dev::eth::MinerType, std::string&, unsigned int): error: undefined reference to 'jsonrpc::JsonRpcException::JsonRpcException(int, std::string const&)'
/tmp/ccZfigRN.ltrans0.ltrans.o:<artificial>:function MinerCLI::doFarm(dev::eth::MinerType, std::string&, unsigned int): error: undefined reference to 'Json::Value::toStyledString() const'
/tmp/ccZfigRN.ltrans0.ltrans.o:<artificial>:function MinerCLI::doFarm(dev::eth::MinerType, std::string&, unsigned int): error: undefined reference to 'jsonrpc::JsonRpcException::JsonRpcException(int, std::string const&)'
/tmp/ccZfigRN.ltrans0.ltrans.o:<artificial>:function MinerCLI::doBenchmark(dev::eth::MinerType, bool, unsigned int, unsigned int, unsigned int): error: undefined reference to 'jsonrpc::HttpClient::HttpClient(std::string const&)'
/tmp/ccZfigRN.ltrans0.ltrans.o:<artificial>:function MinerCLI::doBenchmark(dev::eth::MinerType, bool, unsigned int, unsigned int, unsigned int): error: undefined reference to 'jsonrpc::Client::CallMethod(std::string const&, Json::Value const&)'
/tmp/ccZfigRN.ltrans0.ltrans.o:<artificial>:function MinerCLI::doBenchmark(dev::eth::MinerType, bool, unsigned int, unsigned int, unsigned int): error: undefined reference to 'Json::Value::toStyledString() const'
/tmp/ccZfigRN.ltrans0.ltrans.o:<artificial>:function MinerCLI::doBenchmark(dev::eth::MinerType, bool, unsigned int, unsigned int, unsigned int): error: undefined reference to 'jsonrpc::JsonRpcException::JsonRpcException(int, std::string const&)'
/tmp/ccZfigRN.ltrans17.ltrans.o:<artificial>:function EthStratumClient::processReponse(Json::Value&): error: undefined reference to 'Json::Value::asString() const'
/tmp/ccZfigRN.ltrans17.ltrans.o:<artificial>:function EthStratumClient::readResponse(boost::system::error_code const&, unsigned long): error: undefined reference to 'Json::Reader::parse(std::string const&, Json::Value&, bool)'
/tmp/ccZfigRN.ltrans17.ltrans.o:<artificial>:function EthStratumClient::readResponse(boost::system::error_code const&, unsigned long): error: undefined reference to 'Json::Reader::getFormattedErrorMessages() const'
/tmp/ccZfigRN.ltrans18.ltrans.o:<artificial>:function EthStratumClientV2::processReponse(Json::Value&): error: undefined reference to 'Json::Value::get(std::string const&, Json::Value const&) const'
/tmp/ccZfigRN.ltrans22.ltrans.o:<artificial>:function EthStratumClientV2::workLoop(): error: undefined reference to 'Json::Reader::parse(std::string const&, Json::Value&, bool)'
/tmp/ccZfigRN.ltrans22.ltrans.o:<artificial>:function EthStratumClientV2::workLoop(): error: undefined reference to 'Json::Reader::getFormattedErrorMessages() const'
collect2: error: ld returned 1 exit status
ethminer/CMakeFiles/ethminer.dir/build.make:113: recipe for target 'ethminer/ethminer' failed
make[2]: *** [ethminer/ethminer] Error 1
CMakeFiles/Makefile2:436: recipe for target 'ethminer/CMakeFiles/ethminer.dir/all' failed
make[1]: *** [ethminer/CMakeFiles/ethminer.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by dublinus** [comment]
Did you make sure to `sudo apt install libjsonrpccpp-dev`?

**Comment by Hukuta** [comment]
And I found this:

> sudo apt-gethttps://github.com/Genoil/cpp-ethereum/blob/master/README.md -y install software-properties-common

in README.md file
