### ISSUE TITLE
reference error on make -j8 ubuntu 16.04

### ISSUE THREAD

**Issue by amel00** [Genoil/cpp-ethereum#266]
I keep getting this error on install

/home/russ/cpp-ethereum/libethcore/EthashCUDAMiner.cpp: In member function ‘workLoop’:
/home/russ/cpp-ethereum/libethcore/EthashCUDAMiner.cpp:202:96: warning: ‘startN’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   m_miner->search(w.headerHash.data(), upper64OfBoundary, *m_hook, (w.exSizeBits >= 0), startN);
                                                                                                ^
/home/russ/cpp-ethereum/libethcore/EthashCUDAMiner.cpp:199:12: note: ‘startN’ was declared here
   uint64_t startN;
            ^
/tmp/ccgJRx2q.ltrans19.ltrans.o:<artificial>:__fatDeviceText: error: undefined reference to 'fatbinData'
collect2: error: ld returned 1 exit status
ethminer/CMakeFiles/ethminer.dir/build.make:118: recipe for target 'ethminer/ethminer' failed
make[2]: *** [ethminer/ethminer] Error 1
CMakeFiles/Makefile2:493: recipe for target 'ethminer/CMakeFiles/ethminer.dir/all' failed
make[1]: *** [ethminer/CMakeFiles/ethminer.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

any help would be appreciated

**Comment by fmarchenko** [comment]
I have the same problem, I can not find a solution to this problem, but with the parameter `cmake -DBUNDLE = miner ..` everything is fine, but I'm not sure what CUDA is.
I will be very glad of any help, too!

**Comment by mucbayhias** [comment]
same problem. want to mention, before  i did 

git clone https://github.com/Genoil/cpp-ethereum/
cd cpp-ethereum/
git checkout 110
mkdir build
cd build
cmake -DBUNDLE=cudaminer ..
make -j8

**Comment by deletexiumu** [comment]
I have same problem.
I try the method，but the problem still exists
> git clone https://github.com/Genoil/cpp-ethereum/
cd cpp-ethereum/
git checkout 110
mkdir build
cd build
cmake -DBUNDLE=cudaminer ..
make -j8

**Comment by mucbayhias** [comment]
Workaround:
In the fork https://github.com/ethereum-mining/ethminer there are binaries that work with cuda and run stable, at least on my ubuntu 14.04

**Comment by amel00** [comment]
So I was able to get it working on 16.04 but re downloading and following the readme instructions instead of the ones posted everywhere, they seemed the same but don't know the difference.. 
Gave me an extra 18% hashrate

**Comment by JHGitty** [comment]
Hey! You are writing an issue inside the "genoil" ethminer which does not get updated anymore. Please check out the new ethminer fork from 'chfast'.

This is the new repository:
https://github.com/ethereum-mining/ethminer/

You can find the new releases here:
https://github.com/ethereum-mining/ethminer/releases

If the issue still occurs with the new ethminer there please write a new issue here:
https://github.com/ethereum-mining/ethminer/issues
